name: Run tests
env: 
  TIME_ENV: 1
on:
  pull_request:
    branches: [ master ]

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - name: Master checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run fetch

    - name: Upload time for master
      uses: actions/upload-artifact@v1
      with:
        name: time
        path: time.file
  test:
    runs-on: ubuntu-latest
    needs: fetch
    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: pull checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download time for master
      uses: actions/download-artifact@v1
      with:
        name: time
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
